# Generated by Django 4.2.16 on 2024-09-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workboard',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='WorkBoard',
        ),
    ]
